name: Update read count for all posts
on:
  schedule: # Run workflow automatically
    - cron: '0 2 * * *' # Runs every day at midnight at 2 a.m.
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the Github Actions Workflow page directly

jobs:
  update-readme-with-blog:
    name: Update all the posts with their read counts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: requirements
        run: |
          pip install python-frontmatter
          pip install oyaml
          pip install requests
          pip install PyYAML
      - name: update-counts
        run: |
          python ./scripts/read_post_counts.py
      - shell: pwsh
        # Give an id to the step, so we can reference it later
        id: check_file_changed
        run: |
          # Diff HEAD with the previous commit
          $diff = git diff --name-only

          # Check if a file under docs/ or with the .md extension has changed (added, modified, deleted)
          $SourceDiff = $diff | Where-Object { $_ -match '^docs/' -or $_ -match '.md$' }
          $HasDiff = $SourceDiff.Length -gt 0

          # Set the output named "docs_changed"
          Write-Host "::set-output name=docs_changed::$HasDiff"
      - name: Commit and push if changed
        if: steps.check_file_changed.outputs.docs_changed == 'True'
        run: |
          git pull origin master
          git add .
          git config --global user.email "sachinmalhotra1993@gmail.com"
          git config --global user.name "edorado93-Github-Action"
          git commit -m "Updated post counts"
          git push origin master
      - name: Merge master into gh-pages
        if: steps.check_file_changed.outputs.docs_changed == 'True'
        run: |
          git fetch --unshallow
          git checkout gh-pages
          git pull
          git merge --no-ff master -m "Auto-merge master back to gh-pages"
          git push
